### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by Ta8Success** [DenizDogan92/Expense_Tracker#1]
@DenizDogan92 
would be really good if you could add these suggestions 
be able to show  Total Expenses beside  Total balance
 should be able to add  , create  and remove his own category 
add note to that action after adding new income or expenses
statistics in the side bar, to calculate spending or income from X date to X date 
Addnew expense button should be a little bit bigger, it's very small in small devices
pie chart  should be below the expenses table rather than being an action to open. takes less action & faster information display

but over all it's a pretty usable app

**Comment by denizdxyz** [comment]
@Ta8Success Thank you for your comments and suggestions. Yes I'm planning to improve this app and make it more usable. 

I agree with your suggestions and I will take them into consideration.

I will make a more user friendly UI/UX and add those features.

Best regards
Deniz
